version: "3.9"

networks:
  media-network:
    driver: bridge

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=PlexServer
    volumes:
      - ./provision/plex:/config
      - ./content/media:/data/media
    network_mode: host
    privileged: true
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/radarr:/config
      - ./content:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media-network

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/sonarr:/config
      - ./content:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media-network

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/lidarr:/config
      - ./content:/data
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks:
      - media-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media-network

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/bazarr:/config
      - ./content:/data
    ports:
      - "6767:6767"
    restart: unless-stopped
    networks:
      - media-network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/qbittorrent:/config
      - ./content/torrents:/data/torrents
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - media-network

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/jackett:/config
    ports:
      - "9117:9117"
    restart: unless-stopped
    networks:
      - media-network

  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/ombi:/config
    ports:
      - "3579:3579"
    restart: unless-stopped
    networks:
      - media-network

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/heimdall:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - media-network

  traktarr:
    image: eafxx/traktarr
    container_name: traktarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - DELAY=2.5
      - SORT=rating
      - NOSEARCH=yes
      - NOTIFICATIONS=yes
      - BLACKLIST=yes
      - RUNNOW=no
      - SKIPUPDATE=no
      - APP_BRANCH=master
    volumes:
      - ./provision/traktarr:/config
    restart: unless-stopped
    networks:
      - media-network

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/sabnzbd:/config
      - ./content/torrents:/data/torrents
    ports:
      - "8085:8080"
    restart: unless-stopped
    networks:
      - media-network

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./provision/lazylibrarian:/config
      - ./content:/data
    ports:
      - "5299:5299"
    restart: unless-stopped
    networks:
      - media-network

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      # Connect to Sonarr
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      # Connect to Radarr
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      # Connect to Lidarr
      - UN_LIDARR_0_URL=http://lidarr:8686
      - UN_LIDARR_0_API_KEY=${LIDARR_API_KEY}
    volumes:
      - ./content:/data
    restart: unless-stopped
    networks:
      - media-network
